<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildProjectDirectory)\..\references\ActiveVersion.props" Condition="Exists('$(MSBuildProjectDirectory)\..\references\ActiveVersion.props')" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SpaceEngineers2ReferenceVersion Condition="'$(SpaceEngineers2ReferenceVersion)' == ''">2.3.0.2798</SpaceEngineers2ReferenceVersion>
    <SpaceEngineers2ReferencesDirectory>$(MSBuildProjectDirectory)\..\references\$(SpaceEngineers2ReferenceVersion)</SpaceEngineers2ReferencesDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="nunit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Kontrol.Adapters.SpaceEngineers2/Kontrol.Adapters.SpaceEngineers2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VRage.Core">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\VRage.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="VRage.Core.Game">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\VRage.Core.Game.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="VRage.Library">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\VRage.Library.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Game2.Client">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\Game2.Client.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Game2.Simulation">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\Game2.Simulation.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="VRage.DCS">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\VRage.DCS.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="VRage.Physics">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\VRage.Physics.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="VRage.Input">
      <HintPath>$(SpaceEngineers2ReferencesDirectory)\VRage.Input.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
